---
- name: Set variable with datetime
  set_fact: backup_db_date="{{ lookup('pipe','date \"+%Y-%m-%d__%H-%M\"') }}"

- name: Create dump from db
  mysql_db:
        state: dump
        name: "{{ client_dbname }}"
        target: "{{ vhosts_path }}/DB_{{ client_dbname }}_{{ backup_db_date }}.sql"
        login_user: root
        login_password: "{{ mysql_root_password }}"

- name: Create dump archive
  archive:
        path: "{{ vhosts_path }}/DB_{{ client_dbname }}_{{ backup_db_date }}.sql"
        dest: "{{ vhosts_path }}/DB_{{ client_dbname }}_{{ backup_date }}.sql.bz2"
        format: bz2

- name: Copy archive from remote to local
  fetch: 
        src: "{{ vhosts_path }}/DB_{{ client_dbname }}_{{ backup_date }}.sql.bz2"
        dest: "backup/DB_{{ client_dbname }}_{{ backup_date }}.sql.bz2"
        flat: yes

- name: Remove archive and dump from remote host
  file:
        path: "{{ item }}"
        state: absent
  with_items:
        - "{{ vhosts_path }}/DB_{{ client_dbname }}_{{ backup_date }}.sql.bz2"
        - "{{ vhosts_path }}/DB_{{ client_dbname }}_{{ backup_db_date }}.sql"
  
