---
- name: Set variable with datetime
  set_fact: backup_date="{{ lookup('pipe','date \"+%Y-%m-%d__%H-%M\"') }}"
    
- name: Create backup archive
  archive:
        path: "{{ vhosts_path }}/{{ client_site_name }}"
        dest: "{{ vhosts_path }}/WP_{{ client_site_name }}-{{ backup_date }}.bz2"
        format: bz2

- name: Copy archive from remote to local
  fetch:
        src: "{{ vhosts_path }}/WP_{{ client_site_name }}-{{ backup_date }}.bz2"
        dest: "backup/WP_{{ client_site_name }}-{{ backup_date }}.bz2 "
        flat: yes

- name: Remove archive from remote host
  file: 
        path: "{{ vhosts_path }}/WP_{{ client_site_name }}-{{ backup_date }}.bz2"
        state: absent

